version: "3.7"
services:
  web:
    build: "."
    image: "heroku-django-celery-boilerplate"
    volumes:
      - "./:/app"
    ports:
      - "5000:5000"
    depends_on:
      - "db"
      - "rabbitmq"
    env_file:
      - ".env"

  db:
    image: "postgres:12.2-alpine"
    restart: "always"
    volumes:
      - "./docker/.data/postgres:/var/lib/postgresql/data"
    env_file:
      - ".env"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./docker/.data/rabbitmq:/var/lib/rabbitmq"
    env_file:
      - ".env"
